name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Building target file
      run: mvn clean install

  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    needs: build
    
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci

  zap-scan:
    name: DAST-scan
    runs-on: ubuntu-20.04

    needs: build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: ./  # Specify the working directory for this step
        run: docker build -t webgoat-build:latest .

      - name: Run Docker container
        working-directory: ./  # Specify the working directory for this step
        run: docker run -it -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 webgoat-build:latest
